version: '2'

services:
  web:
    image: nginx:1.19.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    restart: always
    
  php:
    build: .
    volumes:
      - ./code:/code
    restart: always

  myadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - mysqldb
    restart: always

  mysqldb:
    image: biarms/mysql:5.7
    container_name: ${MYSQL_HOST}
    env_file: [".env"]
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql:
